name: Commit Files to Website Branch

on:
    push:
        branches:
        - main

jobs:
    commit:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                ref: main

            - name: Create files
              run: python tools/generate_files.py
            
            - name: Commit and push changes
              run: |
                git config --global user.name 'SilicoFlare [action]'
                git config --global user.email 'silicoflare@gmail.com'
                git checkout -b website
                git add .
                git commit -m 'Adding new files'
                git push origin website
